# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "vue"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vue-router"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vee-validate"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sass-loader"
        update-types: ["version-update:semver-major"]
      - dependency-name: "chartjs-plugin-crosshair"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "python"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
